apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_HOST
          value: mongo-nodeport-svc
        - name: MONGO_PORT
          value: "27017"
  restartPolicy: Never
